### PR TITLE
Added github action, upload artifact

### PR DESCRIPTION
**Pull request by kibibites**

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
This won't work at all. You aren't even compiling paperbin. You are just downloading a soon outdated build and make the ci stuck at running a mc server on it that won't stop because no human is gonna interrupt/stop it.

**Comment by AlexProgrammerDE** [comment]
setup.sh is not needed at all btw because you can execute all those commands directly in the workflow file.

**Comment by x4e** [comment]
Please try running the script by yourself before claiming it won't work.

> a soon outdated build

Paper 1.12 is no longer being updated

> running a mc server on it that won't stop

Minecraft servers automatically quit if the eula has not been agreed to

**Comment by x4e** [comment]
Thank you @sourTaste000 , this is very good.

In the future it will be desirable to make this also compile the native library but for now thats not too much of a worry.

Thanks.

**Comment by AlexProgrammerDE** [comment]
oops...
Sorry I must have misread the workflow file then. Sorry for interrupting you.

**Pull request merged**
